### ISSUE TITLE
Connecting through znc, does not monitor channel on certain trackers.

### ISSUE THREAD

**Issue by Nodens-** [autodl-community/autodl-trackers#215]
For example configuring through znc AR or Apollo works properly.
Configuring RED or MAM does not work unless you modify the .tracker file and replace the irc server with the address of the znc server.

Taking an educated guess I'd say the irc server address is being checked somewhere instead of the tracker name for those trackers.

**Comment by thebigmunch** [comment]
This would be the wrong repo for this issue if that were the case, but it's not.

I see that MAM and Redacted have different network names: ``ANONAMOUSE->MYANONAMOUSE`` and ``Scratch Network -> Scratch-Network``.

**Comment by Nodens-** [comment]
Sorry I thought this was the proper repo for anything tracker related.

A. If it's a matter of network names then why changing the irc server address in the tracker file fixes monitoring? Is it because irc server address acts as a fallback in the check?

B. You closed the issue without a commit fixing it? If it's the network-names should it be fixed in the .tracker files?

**Comment by thebigmunch** [comment]
Because you had no idea whether this was or was caused by. You still don't. That makes it inappropriate for any issue tracker. You should have brought this to the support channel instead of littering the issue tracker. That's why I closed this. From your response, it seems you didn't even bother try changing the network names to see if that changed anything.
